alias | awk -F'[ =]' '{print $2}'
alias vtop='vtop --theme seti'
alias wunderlist='/usr/bin/chromium-browser --profile-directory=Default --app-id=ojcflmmmcfpacggndoaaflkmcoblhnbh'
alias keep='/usr/bin/chromium-browser --profile-directory=Default --app-id=hmjkmjkepdijhoojdojkdfohbdgmmhki'
alias wpr='~/.config/i3/wp.sh'
alias i3conf='vim ~/.config/i3/config'
alias feh='feh --bg-scale'
alias wp='cd ~/Pictures/Wallpaper/ && ls -sa'
alias won='nmcli radio wifi on'
alias woff='nmcli radio wifi off'
alias qcad='./opt/qcad-3.21.3-trial-linux-x86_64/qcad'
alias cdblog='cd /media/hisfantor/data/documents/github/jekyll/'
