alias | awk -F'[ =]' '{print $2}'
alias vtop='vtop --theme seti'
alias wunderlist='/usr/bin/chromium-browser --profile-directory=Default --app-id=oigmhadmggomfkhijpdfggkbakaihijo'
alias wpr='~/.config/i3/wp.sh'
alias i3conf='vim ~/.config/i3/config'
alias blog='cd ~/Documents/webstuff/blog/content/post'
alias feh='feh --bg-scale'
alias wp='cd ~/Pictures/Wallpaper/ && ls -sa'
alias won='nmcli radio wifi on'
alias woff='nmcli radio wifi off'
